anabik:
  elasticsearch:
    host: localhost:9200
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      elastic:
        enabled: true
